/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Display;

/**
 *
 * @author rolae
 */
public class frmstart extends javax.swing.JFrame {

    /**
     * Creates new form frmstart
     */
    public frmstart() {
        initComponents();
        this.setExtendedState(frmstart.MAXIMIZED_BOTH);
        this.setTitle(" Hair Solutions");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desk = new javax.swing.JDesktopPane();
        lblidperson = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lbllastname = new javax.swing.JLabel();
        lblaccess = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnusysappointments = new javax.swing.JMenu();
        mnuarchive = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        mnuappointments = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        mnusetup = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnutools = new javax.swing.JMenu();
        mnuhelp = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuexit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desk.setBackground(new java.awt.Color(102, 204, 255));

        lblidperson.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblidperson.setText("jLabel1");
        desk.add(lblidperson);
        lblidperson.setBounds(20, 30, 150, 14);

        lblname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblname.setText("jLabel2");
        desk.add(lblname);
        lblname.setBounds(20, 60, 150, 14);

        lbllastname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbllastname.setText("jLabel3");
        desk.add(lbllastname);
        lbllastname.setBounds(20, 90, 150, 14);

        lblaccess.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblaccess.setText("jLabel4");
        desk.add(lblaccess);
        lblaccess.setBounds(20, 120, 150, 14);

        mnusysappointments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/home.png"))); // NOI18N
        mnusysappointments.setMnemonic('f');
        mnusysappointments.setText("Home");
        menuBar.add(mnusysappointments);

        mnuarchive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/products & services.png"))); // NOI18N
        mnuarchive.setMnemonic('e');
        mnuarchive.setText("Services & Products");

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/services.png"))); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Services");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        mnuarchive.add(cutMenuItem);

        copyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        copyMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/products.jpg"))); // NOI18N
        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Products");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        mnuarchive.add(copyMenuItem);

        menuBar.add(mnuarchive);

        mnuappointments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/records.png"))); // NOI18N
        mnuappointments.setMnemonic('h');
        mnuappointments.setText("Records");

        contentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/clients.jpg"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Customers Records");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        mnuappointments.add(contentMenuItem);

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/employees.png"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Add New Client");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        mnuappointments.add(aboutMenuItem);

        menuBar.add(mnuappointments);

        mnusetup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/settings.png"))); // NOI18N
        mnusetup.setText("Settings");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/users&access.png"))); // NOI18N
        jMenuItem1.setText("Users & Access");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnusetup.add(jMenuItem1);

        menuBar.add(mnusetup);

        mnutools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/tools.png"))); // NOI18N
        mnutools.setText("Tools");
        menuBar.add(mnutools);

        mnuhelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/help.png"))); // NOI18N
        mnuhelp.setText("Help");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("About");
        mnuhelp.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Help");
        mnuhelp.add(jMenuItem3);

        menuBar.add(mnuhelp);

        mnuexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/exit.jpg"))); // NOI18N
        mnuexit.setText("Exit");
        mnuexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuexitMouseClicked(evt);
            }
        });
        menuBar.add(mnuexit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desk, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desk, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        frmservice form =new frmservice();
        desk.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        // TODO add your handling code here:
        frmproduct form =new frmproduct();
        desk.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        frmclient form =new frmclient();
        desk.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        frmemployee form =new frmemployee();
        desk.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuexitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuexitMouseClicked

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
        frmappointment form = new frmappointment();
        desk.add(form);
        form.toFront();
        form.setVisible(true);
        frmappointment.txtidemployee.setText(lblidperson.getText());
        frmappointment.txtemployee.setText(lblname.getText() + " " + lbllastname.getText());
        frmappointment.iduser=Integer.parseInt(lblidperson.getText());
    }//GEN-LAST:event_contentMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmstart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmstart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmstart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmstart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmstart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desk;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    public static javax.swing.JLabel lblaccess;
    public static javax.swing.JLabel lblidperson;
    public static javax.swing.JLabel lbllastname;
    public static javax.swing.JLabel lblname;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuappointments;
    public static javax.swing.JMenu mnuarchive;
    private javax.swing.JMenu mnuexit;
    private javax.swing.JMenu mnuhelp;
    public static javax.swing.JMenu mnusetup;
    private javax.swing.JMenu mnusysappointments;
    private javax.swing.JMenu mnutools;
    // End of variables declaration//GEN-END:variables

}
